#!/bin/sh

# Let the kernal know that we are using raw socket to receive remote connections
# and therefore we don't want the kernal to drop outgoing TCP RST packets
sudo iptables -A OUTPUT -p tcp --tcp-flags RST RST -j DROP

# Run Python Program
sudo python ./main.py $1